on: push
name: ðŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest

    steps:
    # - uses: shivammathur/setup-php@v2
    #   with:
    #     php-version: '8.0'

    - name: ðŸšš Get latest code
      uses: actions/checkout@v4
    
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    
    # sed: ÄÃ¢y lÃ  má»™t cÃ´ng cá»¥ dÃ²ng lá»‡nh dÃ¹ng Ä‘á»ƒ tÃ¬m kiáº¿m vÃ  thay tháº¿ vÄƒn báº£n trong cÃ¡c file.
    # -i: Chá»‰nh sá»­a file trá»±c tiáº¿p mÃ  ko cáº§n táº¡o má»™t file táº¡m thá»i
    # s - substitute: Thay tháº¿ cÃ¡c giÃ¡ trá»‹ trong file
    - name: Modify .env file
      run: |
        sed -i "s|APP_KEY=.*|APP_KEY=base64:5zN9D5KNgvBRaLyIVqXiggoSPKQ/32hECxTjvjFptKQ=|" .env
        sed -i "s|APP_URL=.*|APP_URL=http://web-ecommerce.free.nf|" .env
        sed -i "s|DB_HOST=.*|DB_HOST=sql105.infinityfree.com|" .env
        sed -i "s|DB_PORT=.*|DB_PORT=3306|" .env
        sed -i "s|DB_DATABASE=.*|DB_DATABASE=if0_36848372_web_ecommerce|" .env
        sed -i "s|DB_USERNAME=.*|DB_USERNAME=if0_36848372|" .env
        sed -i "s|DB_PASSWORD=.*|DB_PASSWORD=Namphan181203|" .env
    
    # - name: Config Clearing
    #   run: php artisan config:clear

    # - name: Update Composer dependencies
    #   run: composer update --prefer-dist --no-progress --no-suggest
    
    # - name: Install Dependencies
    #   run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --optimize-autoloader
      
    # - name: Generate key
    #   run: php artisan key:generate

    # - name: Directory Permissions
    #   run: chmod -R 777 storage bootstrap/cache

    # - name: Install npm
    #   run: npm install

    # Cháº¡y lá»‡nh git add file_name --force Ä‘á»ƒ cÃ³ thá»ƒ upload cÃ¡c folder trong .gitignore
    
    # - name: Symbolic link
    #   run: php artisan storage:link

    - name: Fetch ftp-deploy-sync-state.json
      run: |
        ssh -o StrictHostKeyChecking=no user@ftpupload.net 'cat /path/to/ftp-deploy-sync-state.json' > ftp-deploy-sync-state.json

    - name: Read and process ftp-deploy-sync-state.json
      run: |
        cat ftp-deploy-sync-state.json
    
    - name: ðŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftpupload.net
        username: if0_36848372
        password: Namphan181203
        server-dir: /htdocs/
    
    # - name: Run tests
    #   run: php artisan test